name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master', whichever branch you use

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.20.2  # or whatever version you use

      - name: Install dependencies
        run: yarn install  # or 'npm install'

      - name: Build
        run: yarn run build  # or 'npm run build'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
